package com.js.jms.client.producer;

import org.apache.activemq.ActiveMQConnectionFactory;

import javax.jms.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "JMS Producer App running...";
    }

    public static void main(String[] args) throws Exception  {

        System.out.println(new App().getGreeting());

        ActiveMQConnectionFactory cf = new ActiveMQConnectionFactory("tcp://localhost:61616");
		Connection connection = cf.createConnection();
		connection.start();
		Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
		Queue queue = session.createQueue("EVENTS.Q");

//        Context ctx = new InitialContext();
//        Connection connection = ((ConnectionFactory) ctx.lookup("ConnectionFactory")).createConnection();
//        connection.start();
//        Queue queue = (Queue) ctx.lookup("EVENTS.Q");
//        Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);

        MessageProducer sender = session.createProducer(queue);
        TextMessage msg = session.createTextMessage("JMS Event Message Test at: " + getFormattedDate() );
        msg.setStringProperty("ClientType", "Test Producer");
        sender.send(msg);

        System.out.println("Message sent >>> " + msg);
        connection.close();
    }

    public static String getFormattedDate(){
        String pattern = "yyyy-MM-dd HH:mm:ss.SSSZ";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);

        return simpleDateFormat.format(new Date());
    }
}
